const prof=require("./profile");
const E=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const BADGE='<svg class="verified-badge user-verified" viewBox="0 0 18 18" width="20" height="20" role="img" aria-label="Verified user" xmlns="http://www.w3.org/2000/svg"><title>Verified</title><polygon fill="#0099FD" points="9,16 7.1,16.9 5.8,15.2 3.7,15.1 3.4,13 1.5,12 2.2,9.9 1.1,8.2 2.6,6.7 2.4,4.6 4.5,4 5.3,2 7.4,2.4 9,1.1 10.7,2.4 12.7,2 13.6,4 15.6,4.6 15.5,6.7 17,8.2 15.9,9.9 16.5,12 14.7,13 14.3,15.1 12.2,15.2 10.9,16.9"/><polygon fill="#FFFFFF" points="13.1,7.3 12.2,6.5 8.1,10.6 5.9,8.5 5,9.4 8,12.4"/></svg>';
const LOGO='<span class="kiver-inline-logo" aria-label="Kiver" role="img"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img" aria-label="Kiver"><rect width="256" height="256" fill="#fff"/><circle cx="128" cy="58" r="17" fill="#090909"/><rect x="123" y="70" width="10" height="30" rx="5" fill="#090909"/><rect x="54" y="91" width="148" height="116" rx="43" fill="#090909"/><rect x="75" y="112" width="106" height="45" rx="23" fill="#fff"/><circle cx="98" cy="134" r="9" fill="#090909"/><circle cx="158" cy="134" r="9" fill="#090909"/><circle cx="127" cy="171" r="18" fill="none" stroke="#fff" stroke-width="8"/><path d="M141 185 L159 203" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"/></svg></span>';
const STYLES=["violet","blue","teal","green","amber","orange","rose","slate"];
const imageSrc=b=>b&&b.telegram_username?"/api/image?u="+encodeURIComponent(b.telegram_username):"";
const month=s=>{try{return new Date(s).toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}catch{return""}};
const head=(title,desc,url,robots,extra="")=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(title)}</title><meta name="description" content="${E(desc)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${E(url)}"><meta property="og:site_name" content="Kiver"><meta property="og:type" content="profile"><meta property="og:title" content="${E(title)}"><meta property="og:description" content="${E(desc)}"><meta property="og:url" content="${E(url)}"><meta name="twitter:card" content="summary"><link rel="manifest" href="/manifest.json"><link rel="icon" href="/favicon.ico?v=8" sizes="48x48"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png?v=8"><link rel="icon" type="image/png" sizes="192x192" href="/icon-192.png?v=8"><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=8"><link rel="stylesheet" href="/app.css">${extra}</head><body>`;
const nav=`<header class="nav"><a class="brand" href="/">${LOGO}<span>Kiver</span></a><nav><a href="/directory">Discover</a><a href="/blog">Blog</a><a href="/submit">For makers</a></nav><div class="nav-actions"><a class="nav-link" href="/login.html">Sign in</a><a class="nav-cta" href="/submit">Launch a tool</a></div></header>`;
const foot=`<footer><div><a class="brand" href="/">${LOGO}<span>Kiver</span></a><p>The discovery marketplace for Telegram tools.</p></div><div class="footer-links"><a href="/directory">Directory</a><a href="/blog">Blog</a><a href="/submit">Submit a tool</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a><a href="/refund.html">Refunds</a></div></footer><script src="/app.js?v=11" defer></script></body></html>`;

module.exports=async(req,res)=>{
 const origin=(req.headers["x-forwarded-proto"]||"https")+"://"+req.headers.host;
 let p=null;
 try{p=await prof.getPublic(String(req.query.user||""))}catch{
  res.status(503).setHeader("Content-Type","text/html; charset=utf-8");return res.end(head("Temporarily unavailable | Kiver","","",origin+"/","noindex,nofollow")+nav+'<main class="product-page"><section class="content-block"><h1>Profile unavailable</h1><p>Please try again in a moment.</p></section></main>'+foot);
 }
 if(!p){
  res.status(404);res.setHeader("Content-Type","text/html; charset=utf-8");
  return res.end(head("Profile not found | Kiver","This Kiver profile does not exist.",origin+"/","noindex,nofollow")+nav+'<main class="product-page"><div class="crumb"><a href="/directory">Directory</a><span>/</span><span>Profile</span></div><section class="content-block"><h1>Profile not found</h1><p>We could not find that maker. <a href="/directory">Browse the directory</a>.</p></section></main>'+foot);
 }
 const url=origin+"/u/"+encodeURIComponent(p.username);
 const style=STYLES.includes(p.avatarStyle)?p.avatarStyle:"violet";
 const name=p.displayName||("@"+p.username);
 const bots=p.bots||[];
 const desc=(p.bio||(name+" is a maker on Kiver with "+bots.length+" Telegram "+(bots.length===1?"tool":"tools")+"."));
 const cards=bots.map(x=>`<a class="compact-card" href="/bot/${encodeURIComponent(x.slug)}"><div class="compact-avatar">${imageSrc(x)?'<img src="'+E(imageSrc(x))+'" alt="">':E((x.name||"B").charAt(0))}</div><div><b>${E(x.name)}</b><p>${E(x.description||x.about||"Telegram tool")}</p><small>\u2191 ${x.upvotes||0} \u00b7 ${E(x.category||"Other")}</small></div></a>`).join("");
 const robots=p.verified?"index,follow,max-image-preview:large":"noindex,follow";
 const ld={"@context":"https://schema.org","@type":"ProfilePage",url,mainEntity:{"@type":"Person",name,alternateName:"@"+p.username,description:p.bio||undefined,url}};
 const html=head(name+" (@"+p.username+") | Kiver",desc,url,robots)+nav+
 `<main class="product-page"><div class="crumb"><a href="/directory">Directory</a><span>/</span><span>@${E(p.username)}</span></div><section class="pf-hero"><div class="pf-avatar pf-avatar-lg pf-c-${style}" aria-hidden="true">${E(String(p.displayName||p.username).charAt(0).toUpperCase())}</div><div class="pf-hero-copy"><h1><span>${E(name)}</span>${p.verified?BADGE:""}</h1><div class="pf-handle">@${E(p.username)}</div>${p.bio?'<p class="pf-bio">'+E(p.bio)+'</p>':""}<div class="pf-stats"><span>Joined <b>${E(month(p.joinedAt))}</b></span><span><b>${bots.length}</b> ${bots.length===1?"tool":"tools"}</span><span><b>${p.reviews||0}</b> ${p.reviews===1?"review":"reviews"}</span></div>${p.verified?'<p class="pf-verified-note">Verified maker on Kiver</p>':""}</div></section>${bots.length?'<section class="content-block"><div class="section-head"><div><span class="eyebrow">PUBLISHED</span><h2>Tools by '+E(name)+'</h2></div></div><div class="compact-grid">'+cards+"</div></section>":'<section class="content-block"><p class="muted">No published tools yet.</p></section>'}</main>`+foot.replace("</body></html>",`<script type="application/ld+json">${JSON.stringify(ld).replace(/</g,"\\u003c")}</script></body></html>`);
 res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Cache-Control","s-maxage=120, stale-while-revalidate=600");res.end(html);
};
