const db=require("../lib/db");
const esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
module.exports=async(req,res)=>{
 const origin=(req.headers["x-forwarded-proto"]||"https")+"://"+req.headers.host;
 const top=await db.list({sort:"top",limit:8});
 const fresh=await db.list({sort:"new",limit:8});
 const cards=top.map(b=>`<a class="launch-card" href="/bot/${encodeURIComponent(b.slug)}"><div class="launch-img">${b.image_url?'<img src="'+esc(b.image_url)+'" alt="'+esc(b.name)+' logo">':'<span>'+esc((b.name||"B").charAt(0))+'</span>'}</div><div class="launch-body"><div class="card-meta"><span>${esc(b.category||"Other")}</span><b>↑ ${b.upvotes||0}</b></div><h3>${esc(b.name)}</h3><p>${esc(b.description||"Telegram bot")}</p><small>@${esc(b.telegram_username)}</small></div></a>`).join("");
 const freshCards=fresh.slice(0,6).map(b=>`<a class="compact-card" href="/bot/${encodeURIComponent(b.slug)}"><div class="compact-avatar">${b.image_url?'<img src="'+esc(b.image_url)+'" alt="">':esc((b.name||"B").charAt(0))}</div><div><b>${esc(b.name)}</b><p>${esc(b.description||"Telegram bot")}</p><small>↑ ${b.upvotes||0} · ${esc(b.category||"Other")}</small></div></a>`).join("");
 const body=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fff"><meta name="description" content="Kiver is the discovery marketplace for Telegram bots. Find useful AI, productivity, finance, utility, gaming and community bots — then launch yours."><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(origin)}/"><link rel="manifest" href="/manifest.json"><link rel="stylesheet" href="/app.css"><title>Kiver — Discover the best Telegram bots</title><link rel="icon" href="/kiver-logo.svg"><link rel="apple-touch-icon" href="/kiver-logo.svg"><meta name="theme-color" content="#ffffff"></head><body>
<header class="nav"><a class="brand" href="/"><img class="brand-mark brand-logo" src="/kiver-logo.svg" alt="Kiver"><span>Kiver</span></a><nav><a href="/directory">Discover</a><a href="/category/ai">Categories</a><a href="/submit">For makers</a></nav><div class="nav-actions"><a class="nav-link" href="/login.html">Sign in</a><a class="nav-cta" href="/submit">Launch a bot</a></div></header>
<main>
<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="live-dot"></span> The Telegram bot marketplace</div><h1>Find the Telegram bots<br><em>worth adding.</em></h1><p class="hero-lede">Kiver is where people discover, compare and recommend the bots that make Telegram more useful. Search the directory or launch something you built.</p><form class="hero-search" action="/directory" method="get"><span>⌕</span><input name="q" placeholder="Search bots, use cases, or @usernames" aria-label="Search Telegram bots"><button>Search</button></form><div class="hero-links"><a href="/directory?sort=new">Recently launched →</a><a href="/directory?sort=top">Most upvoted →</a></div></div><div class="hero-art"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="hero-card hero-card-main"><img class="mini-k" src="/kiver-logo.svg" alt="Kiver"><div><strong>Telegram, curated.</strong><small>Find something useful today</small></div><b>↗</b></div><div class="float-card float-one"><span class="float-icon">✦</span><div><strong>AI assistants</strong><small>Work smarter in Telegram</small></div></div><div class="float-card float-two"><span class="float-icon">↗</span><div><strong>Finance</strong><small>Markets, alerts & tools</small></div></div></div></section>
<section class="home-feed"><div class="section-head"><div><span class="eyebrow">TOP DISCOVERIES</span><h2>What people are finding</h2></div><a class="text-link" href="/directory">View all bots →</a></div><div class="launch-grid">${cards||'<div class="empty-feed"><strong>The directory is just getting started.</strong><span>Be one of the first makers to launch.</span><a href="/submit">Submit your bot →</a></div>'}</div></section>
<section class="fresh-section"><div class="section-head"><div><span class="eyebrow">JUST LAUNCHED</span><h2>Fresh on Kiver</h2></div><a class="text-link" href="/directory?sort=new">See newest →</a></div><div class="compact-grid">${freshCards||'<p class="muted">New bots will appear here as makers submit them.</p>'}</div></section>
<section class="category-strip"><div class="section-head"><div><span class="eyebrow">EXPLORE BY USE CASE</span><h2>There’s a bot for that.</h2></div></div><div class="category-grid"><a href="/category/ai"><span>✦</span><b>AI & assistants</b><small>Chat, agents, automation</small></a><a href="/category/productivity"><span>◫</span><b>Productivity</b><small>Workflows, notes, reminders</small></a><a href="/category/finance"><span>↗</span><b>Finance</b><small>Markets, money, alerts</small></a><a href="/category/utilities"><span>⌁</span><b>Utilities</b><small>Tools that save time</small></a><a href="/category/games"><span>◇</span><b>Games</b><small>Play without leaving Telegram</small></a><a href="/category/community"><span>◎</span><b>Community</b><small>Groups, discovery, social</small></a></div></section>
<section class="maker-section"><div class="maker-copy"><span class="eyebrow">FOR TELEGRAM MAKERS</span><h2>Built a bot?<br><em>Give it a place to be found.</em></h2><p>Kiver turns a public Telegram bot link into a permanent discovery page with a searchable listing, community votes and a shareable URL.</p><a class="dark-button" href="/submit">Launch your bot on Kiver <span>→</span></a></div><div class="maker-points"><div><b>01</b><span><strong>Paste your t.me link</strong><small>We pull public metadata automatically.</small></span></div><div><b>02</b><span><strong>Choose a category</strong><small>Show up where people already browse for your use case.</small></span></div><div><b>03</b><span><strong>Build public proof</strong><small>Collect discovery, votes and community feedback.</small></span></div></div></section>
<section class="seo-story"><div><span class="eyebrow">THE TELEGRAM BOT DIRECTORY</span><h2>A public index for the software living inside Telegram.</h2></div><div class="story-copy"><p>Telegram bots turn conversations into software. They can answer questions, automate workflows, monitor markets, translate files, run games, manage communities and deliver services without asking users to leave the app.</p><p>Kiver makes that ecosystem easier to navigate. Search by bot name, Telegram username, category or what you actually need to accomplish. Each approved listing has a permanent public page designed to be shared, discovered and indexed.</p><p>If you build Telegram bots, Kiver gives your project a home beyond the chat link: a clean product page, a place in the directory and a public surface where users can discover what you made.</p></div></section>
<section class="final-cta"><span class="eyebrow">YOUR NEXT BOT IS HERE</span><h2>Discover something useful.</h2><a class="dark-button" href="/directory">Explore the directory <span>→</span></a></section>
</main><footer><div><a class="brand" href="/"><img class="brand-mark brand-logo" src="/kiver-logo.svg" alt="Kiver"><span>Kiver</span></a><p>The discovery marketplace for Telegram bots.</p></div><div class="footer-links"><a href="/directory">Directory</a><a href="/submit">Submit a bot</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></div><small>© Kiver. Discover useful software, one bot at a time.</small></footer>
<script src="/app.js" defer></script><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"WebSite","name":"Kiver","url":origin+"/","description":"Discovery marketplace for Telegram bots.","potentialAction":{"@type":"SearchAction","target":origin+"/directory?q={search_term_string}","query-input":"required name=search_term_string"}}).replace(/</g,"\\u003c")}</script></body></html>`;
 res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Cache-Control","s-maxage=60, stale-while-revalidate=300");res.end(body);
};